services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotnet-template-api:latest
    ports:
      - "5000:80"
    depends_on:
      - postgres
    env_file:
      - .env # see below
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=${DB_CONNECTION}

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
